name: tcga_ml_brca
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - r-base=4.2.2
  - r-tidyverse
  - r-biocmanager
  - r-yaml
  - pandas=2.1.4
  - numpy=1.26.2
  - scikit-learn=1.3.2
  - xgboost=2.0.3
  - networkx=3.2.1
  - pytorch=2.1.2
  - torch-geometric=2.4.0
  - shap=0.44.0
  - matplotlib=3.8.2
  - seaborn=0.13.0
  - pyyaml=6.0.1
  - pip
